title: Ellim의 기록
description: Ellim이 만들고, 살피고, 다시 고친 것에 대한 기록
url: "https://ellim2.github.io"
baseurl: ""
lang: ko
timezone: Asia/Seoul
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
